### ISSUE TITLE
Use libhandy to pan the map with 2 figers

### ISSUE THREAD

**Issue by hanaral** [ryonakano/atlas#5] opened 2021-11-23 16:25 UTC
It would be far nicer to be able to use 1 to 1 panning like with Maps on MacOS.
However it might require manual implementation using the libhandy gesture tracker.

**Comment by ryonakano** [comment] 2023-03-09 10:47
Hi @hanaral, I'm sorry that it took so long time to look into this.

I'm now working on the next release of Atlas, and it uses newer libraries like GTK 4 and Granite 7. This version-up also comes to the map library. Previously we used libchamplain (which only supports GTK 3), and now we use [libshumate](https://gitlab.gnome.org/GNOME/libshumate).

And looks like libshumate itself implements zooming gestures:

https://gitlab.gnome.org/GNOME/libshumate/-/blob/1.0.3/shumate/shumate-map.c#L834-872

―which means we can use gestures in Atlas on its own! I confirmed zooming with 2 fingers and rotating works on my MacBook Air. So, I'l close this issue as completed. Thank you for your idea :heart:

**Closed as completed by ryonakano** 2023-03-09 10:47 UTC
Labels: Priority: Wishlist, Status: Confirmed
